### PR TITLE
cmake, resolver, types: include executable component if found

### PR DESCRIPTION
**Pull request by RichardRohac**
This allows for generating executable packages, usually found in 'applications' folder.

### CODE REVIEW

**Comment by frutiger** [comment]
@RichardRohac I force pushed your branch to pick up https://github.com/frutiger/bdemeta/commit/df2bd4bd216a0d5822e8e759062cd2a319c57d1a. Please rebase your local clone(s) to sync up.

**Comment by frutiger** [comment]
@RichardRohac thanks for submitting this PR. I wanted to take [a slightly different approach](https://github.com/frutiger/bdemeta/commit/eecb0977a03429178994a96484c15aa319693314) than what you have done. In particular I wanted to introduce a new type `Application` that describes application targets instead of adding an `is_executable` attribute to existing targets. Since _application_ targets are very similar to _package_ targets, I created a derived type to support this.

I have tested my change locally, but can you please check if my branch works for your use case? If it does, I would prefer to land that instead.

Thanks again!

**Comment by frutiger** [comment]
@RichardRohac after our private conversation I found and fixed the bug you raised about implicit `<name>.m.cpp` inclusion. Please try again with the updated [https://github.com/frutiger/bdemeta/tree/applications](applications) branch.

**Comment by RichardRohac** [comment]
Thank you, I tested your branch and it works fine.

**Pull request closed without merging**
